language: scala

scala:
  - 2.11.7
  - 2.11.8
  - 2.12.0
  - 2.12.1

sudo: false

jdk:
  - oraclejdk8

env:
  - TRAVIS_NODE_VERSION="5.0.0"
  - TRAVIS_NODE_VERSION="5.1.0"
  - TRAVIS_NODE_VERSION="5.1.1"
  - TRAVIS_NODE_VERSION="5.2.0"
  - TRAVIS_NODE_VERSION="5.3.0"
  - TRAVIS_NODE_VERSION="5.4.0"
  - TRAVIS_NODE_VERSION="5.5.0"
  - TRAVIS_NODE_VERSION="5.6.0"
  - TRAVIS_NODE_VERSION="5.7.0"
  - TRAVIS_NODE_VERSION="5.7.1"
  - TRAVIS_NODE_VERSION="5.8.0"
  - TRAVIS_NODE_VERSION="5.9.0"
  - TRAVIS_NODE_VERSION="5.9.1"
  - TRAVIS_NODE_VERSION="5.10.0"
  - TRAVIS_NODE_VERSION="5.10.1"
  - TRAVIS_NODE_VERSION="5.11.0"
  - TRAVIS_NODE_VERSION="5.11.1"
  - TRAVIS_NODE_VERSION="5.12.0"
  - TRAVIS_NODE_VERSION="6.1.0"
  - TRAVIS_NODE_VERSION="6.2.0"
  - TRAVIS_NODE_VERSION="6.2.1"
  - TRAVIS_NODE_VERSION="6.2.2"
  - TRAVIS_NODE_VERSION="6.3.0"
  - TRAVIS_NODE_VERSION="6.4.0"
  - TRAVIS_NODE_VERSION="6.5.0"
  - TRAVIS_NODE_VERSION="6.6.0"
  - TRAVIS_NODE_VERSION="6.7.0"
  - TRAVIS_NODE_VERSION="6.8.0"
  - TRAVIS_NODE_VERSION="6.8.1"
  - TRAVIS_NODE_VERSION="6.9.0"
  - TRAVIS_NODE_VERSION="6.9.1"
  - TRAVIS_NODE_VERSION="6.9.2"
  - TRAVIS_NODE_VERSION="6.9.3"
  - TRAVIS_NODE_VERSION="6.9.4"
  - TRAVIS_NODE_VERSION="6.9.5"
  - TRAVIS_NODE_VERSION="6.10.0"
  - TRAVIS_NODE_VERSION="7.0.0"
  - TRAVIS_NODE_VERSION="7.1.0"
  - TRAVIS_NODE_VERSION="7.2.0"
  - TRAVIS_NODE_VERSION="7.2.1"
  - TRAVIS_NODE_VERSION="7.3.0"
  - TRAVIS_NODE_VERSION="7.4.0"
  - TRAVIS_NODE_VERSION="7.5.0"
  - TRAVIS_NODE_VERSION="7.6.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
